# Generated by Django 5.1.3 on 2024-11-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_series_id', models.CharField(max_length=50, unique=True)),
                ('series_name', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('month_year', models.CharField(max_length=20)),
                ('tp', models.CharField(max_length=50)),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.team', to_field='team_unique_id')),
            ],
        ),
    ]
