# Generated by Django 5.1.3 on 2024-11-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='tp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
