# Generated by Django 5.1.3 on 2024-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_time', models.CharField(blank=True, max_length=50, null=True)),
                ('match_type', models.CharField(blank=True, max_length=100, null=True)),
                ('match_status', models.CharField(blank=True, max_length=100, null=True)),
                ('winning_team', models.CharField(blank=True, max_length=100, null=True)),
                ('match_link', models.URLField(unique=True)),
            ],
        ),
    ]
