# Generated by Django 5.1.3 on 2024-11-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_remove_match_match_status_remove_match_match_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(blank=True, max_length=255, null=True)),
                ('balls_in_each_over', models.TextField(blank=True, null=True)),
                ('bowling_status', models.CharField(blank=True, max_length=255, null=True)),
                ('match_duration', models.IntegerField(blank=True, null=True)),
                ('team_info', models.CharField(blank=True, max_length=255, null=True)),
                ('match_ip_addresses', models.CharField(blank=True, max_length=255, null=True)),
                ('run_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('match_ips_or_stats', models.TextField(blank=True, null=True)),
                ('match_status', models.CharField(blank=True, max_length=255, null=True)),
                ('player_performance_code', models.CharField(blank=True, max_length=255, null=True)),
                ('player_score', models.IntegerField(blank=True, null=True)),
                ('bowling_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_code', models.IntegerField(blank=True, null=True)),
                ('event_data', models.CharField(blank=True, max_length=255, null=True)),
                ('match_code', models.CharField(blank=True, max_length=255, null=True)),
                ('team_or_player_status', models.CharField(blank=True, max_length=255, null=True)),
                ('match_score', models.CharField(blank=True, max_length=255, null=True)),
                ('runs_in_current_over', models.CharField(blank=True, max_length=255, null=True)),
                ('runs_required', models.CharField(blank=True, max_length=255, null=True)),
                ('match_event_time', models.CharField(blank=True, max_length=255, null=True)),
                ('next_event_time', models.CharField(blank=True, max_length=255, null=True)),
                ('match_status_details', models.CharField(blank=True, max_length=255, null=True)),
                ('batting_code', models.CharField(blank=True, max_length=255, null=True)),
                ('batting_avg', models.IntegerField(blank=True, null=True)),
                ('special_match_code', models.CharField(blank=True, max_length=255, null=True)),
                ('match_code_event', models.IntegerField(blank=True, null=True)),
                ('player_code', models.CharField(blank=True, max_length=255, null=True)),
                ('query_status', models.CharField(blank=True, max_length=255, null=True)),
                ('team_status', models.CharField(blank=True, max_length=255, null=True)),
                ('fielding_position', models.IntegerField(blank=True, null=True)),
                ('play_code', models.CharField(blank=True, max_length=255, null=True)),
                ('team_or_player_status_details', models.CharField(blank=True, max_length=255, null=True)),
                ('team_code', models.CharField(blank=True, max_length=255, null=True)),
                ('player_score_status', models.CharField(blank=True, max_length=255, null=True)),
                ('match_progress', models.CharField(blank=True, max_length=255, null=True)),
                ('player_performance', models.CharField(blank=True, max_length=255, null=True)),
                ('final_score', models.CharField(blank=True, max_length=255, null=True)),
                ('match_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_data', to='match.match', to_field='match_unique_id')),
            ],
        ),
    ]
