# Generated by Django 5.1.3 on 2024-11-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_match_match_unique_id_matchdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='w',
        ),
    ]
